services:
  # Web Service for the combined Node.js application
  - type: web
    name: fast-reflex-game
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    runtime: node 